export const URL_CLIENTES = 'http://localhost:8000/clientes'
export const URL_CLIENTE_CREAR = 'http://localhost:8000/clientes/create/'
export const URL_CLIENTE_EDITAR = 'http://localhost:8000/clientes/edit/'
export const URL_PRODUCTO_EDITAR = 'http://localhost:8000/productos/edit/'
export const URL_CLIENTE_ELIMINAR = 'http://localhost:8000/clientes/delete/'
export const URL_PRODUCTOS = 'http://localhost:8000/productos'
export const URL_PRODUCTO_ELIMINAR = 'http://localhost:8000/productos/delete/'